# Omakase Ruby styling for Rails
inherit_gem: { rubocop-rails-omakase: rubocop.yml }

# Enable line length checking
Layout/LineLength:
  Enabled: true
  Max: 120
  AllowedPatterns:
    - '\A#'
    - 'config\.'

# Array formatting
Layout/ArrayAlignment:
  Enabled: true
  EnforcedStyle: with_first_element

Layout/FirstArrayElementIndentation:
  Enabled: true
  EnforcedStyle: consistent

Layout/MultilineArrayBraceLayout:
  Enabled: true
  EnforcedStyle: new_line

# Hash formatting
Layout/HashAlignment:
  Enabled: true
  EnforcedColonStyle: key
  EnforcedHashRocketStyle: key

Layout/FirstHashElementIndentation:
  Enabled: true
  EnforcedStyle: consistent

Layout/MultilineHashBraceLayout:
  Enabled: true
  EnforcedStyle: new_line

# Method arguments
Layout/ArgumentAlignment:
  Enabled: true
  EnforcedStyle: with_fixed_indentation

Layout/FirstArgumentIndentation:
  Enabled: true
  EnforcedStyle: consistent
# Overwrite or add rules to create your own house style
#
# # Use `[a, [b, c]]` not `[ a, [ b, c ] ]`
# Layout/SpaceInsideArrayLiteralBrackets:
#   Enabled: false
