# Omakase Ruby styling for Rails
inherit_gem: { rubocop-rails-omakase: rubocop.yml }

# Enable line length checking
Layout/LineLength:
  Enabled: true
  Max: 100

# Array formatting

Layout/FirstArrayElementLineBreak:
  Enabled: true

Layout/ArrayAlignment:
  Enabled: true

Layout/FirstArrayElementIndentation:
  Enabled: true
  EnforcedStyle: consistent

Layout/MultilineArrayBraceLayout:
  Enabled: true
  EnforcedStyle: same_line

# Hash formatting
Layout/HashAlignment:
  Enabled: true
  EnforcedHashRocketStyle: table
  EnforcedColonStyle: table

Layout/FirstHashElementIndentation:
  Enabled: true
  EnforcedStyle: consistent

Layout/MultilineHashBraceLayout:
  Enabled: true
  EnforcedStyle: same_line

# Method call formatting
Layout/MultilineMethodCallIndentation:
  Enabled: true
  EnforcedStyle: indented

Layout/ArgumentAlignment:
  Enabled: true

Layout/FirstArgumentIndentation:
  Enabled: true

Layout/MultilineMethodCallBraceLayout:
  Enabled: true
# Overwrite or add rules to create your own house style
#
# # Use `[a, [b, c]]` not `[ a, [ b, c ] ]`
# Layout/SpaceInsideArrayLiteralBrackets:
#   Enabled: false
