name: Ruby

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.4.1"
          bundler-cache: false
          bundler: "2.6.3"

      - name: Install dependencies
        run: |
          bundle config unset deployment
          bundle config set --local path 'vendor/bundle'
          bundle install

      - name: Run tests
        run: |
          bundle exec rails db:create db:schema:load
          bundle exec rspec

      - name: Security scan
        run: bundle exec brakeman --no-pager

      - name: Rubocop
        run: bundle exec rubocop
